# Generated by Django 5.1.4 on 2024-12-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cozinha', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garcom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('restaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cozinha.restaurante')),
            ],
        ),
    ]
