# Generated by Django 5.1.4 on 2024-12-20 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garcom', '0001_initial'),
        ('mesa', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_pedido', models.DateTimeField(auto_now_add=True)),
                ('garcom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garcom.garcom')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.mesa')),
                ('produtos', models.ManyToManyField(to='produto.produto')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.statuspedido')),
            ],
        ),
    ]
