# Generated by Django 5.1.4 on 2024-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.FloatField()),
                ('descricao', models.TextField()),
                ('quantidade', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos')),
                ('ativo', models.BooleanField(default=True)),
                ('categorias', models.ManyToManyField(related_name='produtos', to='produto.categoria')),
            ],
        ),
    ]
